title: Kaizen Coder
email: karthickpdy@gmail.com
description: Become a better developer, day by day!
author: Srinivasan
baseurl: /
url: 'https://kaizencoder.com/'
twitter_username:
github_username: karthickpdy
facebook_username: "srinivasan.chandramouli.7"
linkedin_username: srinivasanchandramouli
highlighter: rouge
comments: true
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
paginate: 5
paginate_path: '/posts/page:num/'
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
